### ISSUE TITLE
docker build image error

### ISSUE THREAD

**Issue by tulid** [chenseanxy/helm-hbase-chart#1]
root@uos-PC:~/jinquan/hbase/helm-hbase-chart/image# ls
Dockerfile  hbase-2.1.0  hbase-2.1.0-bin.tar.gz  Makefile  README.md
root@uos-PC:~/jinquan/hbase/helm-hbase-chart/image# docker build -t chenseanxy/hbase:2.1.0-hadoop3.1.2 .
Sending build context to Docker daemon  809.7MB
Step 1/5 : FROM chenseanxy/hadoop:3.2.1-nolib
 ---> 38502b3d2513
Step 2/5 : ARG VERSION=2.1.0
 ---> Using cache
 ---> 79511bab911d
Step 3/5 : ADD hbase-${VERSION}-bin.tar.gz /opt
 ---> Using cache
 ---> a81c33d27d3b
Step 4/5 : RUN cd /opt && ln -s ./hbase-${VERSION} hbase &&     cp hbase/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar hbase/lib &&     .
 ---> Running in 4369a6f303a5
The command '/bin/sh -c cd /opt && ln -s ./hbase-${VERSION} hbase &&     cp hbase/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar hbase/lib &&     .' returned a non-zero code: 2

i think the error is the reason of that Dockerfile  is error
can you explain what's mean of the “.”  in the Dockerfile line 6

---
FROM chenseanxy/hadoop:3.2.1-nolib

ARG VERSION=

ADD hbase-${VERSION}-bin.tar.gz /opt

RUN cd /opt && ln -s ./hbase-${VERSION} hbase && \
    cp hbase/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar hbase/lib && \
    .

WORKDIR /opt/hbase

**Comment by chenseanxy** [comment]
The "." is basically there to make it look better :p, so that i could still have `&& \` on the last line.

Probably try and remove the ` hbase/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar hbase/lib` part and see if it works? I don't remember much about this now, but this was probably a workaround for a weird pathing issue, and might not be a problem anymore.

**Comment by tulid** [comment]
> The "." is basically there to make it look better :p, so that i could still have `&& \` on the last line.
> 
> Probably try and remove the ` hbase/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar hbase/lib` part and see if it works? I don't remember much about this now, but this was probably a workaround for a weird pathing issue, and might not be a problem anymore.

thank u for your reply.
i remove "&& \ . ". and, the image is built seccessfully. so, I want to confirm with you whether this is feasible. if this is feasible to do so. i think this question can be closed.

**Comment by chenseanxy** [comment]
Oh they probably deprecated the use of `&& \ .`, and thanks for the heads up.
